config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :teams
  resources :divisions do
    resources :teams_in_divisions
  end

  get :tourney, to: 'tourneys#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :teams_in_divisions
  has_many :teams, through: :teams_in_divisions
  has_many :tourneys
end

app/models/match.rb
class Match < ApplicationRecord
  STATUSES = %w[COMPLETED CANCELED ON_TIME].freeze
  RESULTS = %w[WIN DRAW LOSE].freeze

  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_one :chart, class_name: 'TeamsInDivision'
  has_one :division, through: :teams_in_division
  has_many :matches, dependent: :destroy

  scope :not_in_division, -> {
    joins(%{
      LEFT JOIN teams_in_divisions ON teams_in_divisions.team_id = teams.id
      WHERE teams_in_divisions.team_id IS NULL
    })
  }

  def score_in_division
    chart.score
  end
end

app/models/teams_in_division.rb
class TeamsInDivision < ApplicationRecord
  belongs_to :team
  belongs_to :division
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Dry::Monads::Result::Mixin

  private

  def failure_resolver(operation, error_code)
    path = operation.class.to_s.split("::").map(&:underscore).join(".")
    exceptions_path = "errors.#{path}"
    t("#{exceptions_path}.#{error_code}")
  end
end

app/controllers/divisions_controller.rb
# frozen_string_literal: true

class DivisionsController < ApplicationController
  def index
    @divisions = Division.all
  end

  def create
    operation = Operations::Divisions::Create.new
    result = operation.call(division_params.to_h)

    case result
    in Success
      flash[:success] = t('.success')
    in Failure[error_code, errors]
      flash[:error] = failure_resolver(operation, error_code)
    end
    redirect_to divisions_path
  end

  private

  def division_params
    params.require(:division).permit(:name)
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def create
    operation = Operations::Teams::Create.new
    result = operation.call(team_params.to_h)

    case result
    in Success
      flash[:success] = t('.success')
    in Failure[error_code, errors]
      flash[:error] = failure_resolver(operation, error_code)
    end
    redirect_to teams_path
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/controllers/teams_in_divisions_controller.rb
# frozen_string_literal: true

class TeamsInDivisionsController < ApplicationController
  def new
    @teams_in_division = TeamsInDivision.new
  end

  def create
    operation = Operations::TeamsInDivisions::Add.new
    result = operation.call(params[:division_id], team_id)

    case result
    in Success
      flash[:success] = t('.success')
    in Failure[error_code, errors]
      flash[:error] = failure_resolver(operation, error_code)
    end
    redirect_to divisions_path
  end

  private

  def team_id
    params.require(:teams_in_division).permit(:team_id)
  end
end

app/controllers/tourneys_controller.rb
# frozen_string_literal: true

class TourneysController < ApplicationController
  def index
    @divisions = Division.all
  end

  def result
    operation = Operations::Tourneys::Divisions::GetResults.new
    result = operation.call(params[:division_id])

    case result
    in Success
    in Failure
    end
  end

  def play_off
    @teams = Team.ordered_by_score_in_division.first(4)
    operation = Operations::Tourneys::PlayOff::GetResults.new
    result = operation.call(@teams)

    case result
    in Success
    in Failure
    end
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/divisions/index.slim
.container.mt-3
  .container
    .row
      .col.md-6
        = form_with model: @division || Division.new do |f|
            = f.label :name, class: 'form-label'
            = f.text_field :name, class: 'form-control', placeholder: 'Division name'
            = f.submit t('.submit'), class: 'btn btn-primary mt-3'


  .container
    - if @divisions.any?
      - @divisions.each do |division|
        h2 = "##{division.id} #{division.name}"

        = link_to 'Add to division', new_division_teams_in_division_path(division), class: 'btn btn-success mb-3'

        - if division.teams.any?
          table.table
            thead
              tr
                th scope='col' ID
                th scope='col' Name
                th scope='col' Score
            tbody
              - division.teams.each do |team|
                tr
                  th = team.id
                  th = team.name
                  th = team.score_in_division

    - else
      h1 No any divisions yet

app/views/layouts/application.slim
<!DOCTYPE html
html
  head
    title Tournament
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav class="navbar navbar-expand-lg navbar-light bg-light"
      div class="container-fluid"
        a class="navbar-brand" href="/" Tournament
        div class="collapse navbar-collapse" id="navbarNav"
          ul class="navbar-nav"
            li class="nav-item"
              a class="nav-link" href="/teams" Teams
            li class="nav-item"
              a class="nav-link" href="/divisions" Divisions
            li class="nav-item"
              a class="nav-link" href="/tourney" Tourney
    - flash.each do |kind, msg|
      div class="alert-#{kind}"
        = msg
    = yield

app/views/teams_in_divisions/new.slim
.container.mt-3
  .container
    .row
      .col.md-4
        = form_with model: [:division, @teams_in_division], class: 'row g-3' do |f|
          .col-auto
              = f.label :team_id, class: 'visually-hidden'
              = f.select(:team_id, options_for_select(Team.not_in_division.pluck(:name, :id)), { prompt: true }, { class: 'form-select' })
          .col-auto
              = f.submit t('.submit'), class: 'btn btn-primary mb-3'

        = link_to t('.back'), divisions_path

app/views/tourneys/index.slim
h1 Tourneys